version: "3"
services:
  front:
    build:
      image: arom98/rpcw23-frontend:latest<
    ports:
      - 3000:3000
    volumes:
      - ./env_files/.env_front:/app/.env

  auth-api:
    build:
      image: arom98/rpcw23-auth-api:latest
    ports:
      - 3001:3001
    volumes:
      - ./env_files/.env_auth:/app/.env
    depends_on:
      - mongodb_auth

  user-api:
    build:
      image: arom98/rpcw23-user-api:latest
    ports:
      - 3002:3002
    volumes:
      - ./env_files/.env_user:/app/.env
    depends_on:
      - mongodb_user

  data-api:
    build:
      image: arom98/rpcw23-data-api:latest
    ports:
      - 3003:3003
    volumes:
      - ./env_files/.env_data:/app/.env
    depends_on:
      - mongodb_data

  mongodb_auth:
    image: mongo:5.0.16-focal
    container_name: mongodb-auth
    ports:
      - 4001:27017
    restart: unless-stopped

  mongodb_user:
    image: mongo:5.0.16-focal
    container_name: mongodb-user
    ports:
      - 4002:27017
    restart: unless-stopped

  mongodb_data:
    image: mongo:5.0.16-focal
    container_name: mongodb-data-api
    ports:
      - 4003:27017
    restart: unless-stopped
