version: "3"

services:
  mongodb_auth:
    image: mongo:5.0.16-focal
    container_name: mongodb-auth
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - 4001:27017
    # volumes:
    #   - /tmp/mongo-data:/data/db mongo:6-jammy
    restart: unless-stopped
  
  mongodb_user:
    image: mongo:5.0.16-focal
    container_name: mongodb-user
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - 4002:27017
    # volumes:
    #   - /tmp/mongo-data:/data/db mongo:6-jammy
    restart: unless-stopped

  mongodb_data:
    image: mongo:5.0.16-focal
    container_name: mongodb-data-api
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - 4003:27017
    # volumes:
    #   - /tmp/mongo-data:/data/db mongo:6-jammy
    restart: unless-stopped